<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="25" total="29" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-13T15:31:29 IST" name="Suite" finished-at="2022-07-13T15:32:02 IST" duration-ms="33528">
    <groups>
      <group name="sanity">
        <method signature="ClientTest.validateClientSerchResult()[pri:17, instance:com.mobileTest.ClientTest@242b836]" name="validateClientSerchResult" class="com.mobileTest.ClientTest"/>
        <method signature="LoginTest.validateURL()[pri:1, instance:com.mobileTest.LoginTest@130c12b7]" name="validateURL" class="com.mobileTest.LoginTest"/>
        <method signature="LoginTest.validateValidLogin()[pri:3, instance:com.mobileTest.LoginTest@130c12b7]" name="validateValidLogin" class="com.mobileTest.LoginTest"/>
        <method signature="LoginTest.validateareUsernameAndPasswordFieldsDisplayed()[pri:2, instance:com.mobileTest.LoginTest@130c12b7]" name="validateareUsernameAndPasswordFieldsDisplayed" class="com.mobileTest.LoginTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2022-07-13T15:31:29 IST" name="Mobile Sevice" finished-at="2022-07-13T15:32:02 IST" duration-ms="33528">
      <class name="com.mobileTest.ClientTest">
        <test-method signature="validateClientSerchResult()[pri:17, instance:com.mobileTest.ClientTest@242b836]" started-at="2022-07-13T15:31:53 IST" name="validateClientSerchResult" finished-at="2022-07-13T15:31:53 IST" duration-ms="75" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.mobileService.MobileClientPage.clientsearchResult(String)" because "this.client" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.mobileService.MobileClientPage.clientsearchResult(String)" because "this.client" is null
at com.mobileTest.ClientTest.validateClientSerchResult(ClientTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateClientSerchResult -->
      </class> <!-- com.mobileTest.ClientTest -->
      <class name="com.mobileTest.LoginTest">
        <test-method is-config="true" signature="grouping(java.lang.String)[pri:0, instance:com.mobileTest.LoginTest@130c12b7]" started-at="2022-07-13T15:31:29 IST" name="grouping" finished-at="2022-07-13T15:31:53 IST" duration-ms="23744" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- grouping -->
        <test-method signature="validateURL()[pri:1, instance:com.mobileTest.LoginTest@130c12b7]" started-at="2022-07-13T15:31:53 IST" name="validateURL" finished-at="2022-07-13T15:31:53 IST" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateURL -->
        <test-method signature="validateareUsernameAndPasswordFieldsDisplayed()[pri:2, instance:com.mobileTest.LoginTest@130c12b7]" started-at="2022-07-13T15:31:53 IST" name="validateareUsernameAndPasswordFieldsDisplayed" finished-at="2022-07-13T15:31:53 IST" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateareUsernameAndPasswordFieldsDisplayed -->
        <test-method signature="validateValidLogin()[pri:3, instance:com.mobileTest.LoginTest@130c12b7]" started-at="2022-07-13T15:31:53 IST" name="validateValidLogin" finished-at="2022-07-13T15:32:02 IST" duration-ms="9225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateValidLogin -->
      </class> <!-- com.mobileTest.LoginTest -->
    </test> <!-- Mobile Sevice -->
  </suite> <!-- Suite -->
</testng-results>
